### ISSUE TITLE
How to install clang 3.6 in Ubuntu 12.04

### ISSUE THREAD

**Issue by Rafoula** [huangyihe/clang-3.6.0#1]
Hello,
I want to install clang 3.6 on Ubuntu 12.04. How can I do that?
Thanks

**Comment by huangyihe** [comment]
Hi,
I'm not involved in the clang project, this is merely a mirror I used for something else. As for installing clang 3.6, I believe you need to checkout the entire LLVM repository and place the clang folder (this repository) in the appropriate location in the LLVM source tree. LLVM's build system (cmake in my case) should take care of building and installing clang all by itself from there.
